spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://warendy-rds.cssg19lmc183.ap-northeast-2.rds.amazonaws.com:3306/warendy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
  jwt:
    secret-key: secret-key
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: redirect-uri
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
