name: CI-CD

on:
  push:
    branches:
      - main
env:
  S3_BUCKET_NAME: warendy-s3
  RESOURCE_PATH: ./src/main/resources/application.yml
  CODE_DEPLOY_APPLICATION_NAME: CODE-DEPLOY-WARENDY
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: CODE-DEPLOY-GROUP
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set Up MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: warendy
          mysql user: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          mysql password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      - name: Set yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID }}
          spring.security.oauth2.client.registration.kakao.client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
          spring.security.oauth2.client.registration.kakao.redirect-uri: ${{ secrets.KAKAO_REDIRECT_URI }}
          spring.jwt.secret-key: ${{ secrets.SPRING_JWT_SECRET_KEY }}
          spring.datasource.url: ${{ secrets.SPRING_DATASOURCE_URL }}
          spring.datasource.username: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          spring.datasource.password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          spring.kafka.bootstrap-servers: ${{ secrets.KAKFA_BROKER }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip